(() => {
'use strict';
const MQ=window.MQ;if(!MQ)return;
const STORE='mindquest-progress-v3',SESSION='mindquest-session-v3',AGE_KEY='mindquest-age-pathway',VIEW_KEY='mindquest-current-view-v2',ACCOUNT_KEY='mindquest-account-v1',SETTINGS_KEY='mindquest-settings-v1';
const saved=(()=>{try{return JSON.parse(localStorage.getItem(STORE)||'{}')}catch{return {}}})();
let arcadeExitSave=false;
const keyFor=(age,game)=>`${age}:${game}`;
const gameName=id=>({memory:'Memory Lab',detective:'Detective',reflex:'Reflex Arena',builder:'Builder',team:'Team Quest',world:'World Explorer',money:'Money Mission'})[id]||id;
const checkpoint=()=>{const s=MQ.state;return {age:s.age,game:s.game,level:s.level,lives:s.lives,streak:s.streak,bestStreak:s.bestStreak,xp:s.xp,score:s.score,earnedThisRun:s.earnedThisRun,milestonePending:!!s.milestonePending,milestoneLevel:s.milestoneLevel||0,detectiveActivity:s.detectiveActivity||0,memoryActivity:s.memoryActivity||0,reflexActivity:s.reflexActivity||0,builderActivity:s.builderActivity||0,teamActivity:s.teamActivity||0,worldActivity:s.worldActivity||0,moneyActivity:s.moneyActivity||0,skills:s.skills,skillStats:s.skillStats,account:s.account||null,premium:!!s.premium}};
const save=()=>{if(!MQ.state.game||arcadeExitSave)return;saved[keyFor(MQ.state.age,MQ.state.game)]=checkpoint();try{localStorage.setItem(STORE,JSON.stringify(saved));localStorage.setItem(SESSION,JSON.stringify({age:MQ.state.age,game:MQ.state.game}));localStorage.setItem(AGE_KEY,String(MQ.state.age));if(MQ.state.account)localStorage.setItem(ACCOUNT_KEY,JSON.stringify(MQ.state.account));localStorage.setItem(SETTINGS_KEY,JSON.stringify(MQ.state.settings||{}))}catch{}};
const saveAndExit=()=>{if(!MQ.state.game)return;saved[keyFor(MQ.state.age,MQ.state.game)]=checkpoint();try{localStorage.setItem(STORE,JSON.stringify(saved));localStorage.setItem(SESSION,JSON.stringify({age:MQ.state.age,game:MQ.state.game}));localStorage.setItem(AGE_KEY,String(MQ.state.age));localStorage.setItem(VIEW_KEY,'home');if(MQ.state.account)localStorage.setItem(ACCOUNT_KEY,JSON.stringify(MQ.state.account))}catch{}arcadeExitSave=true;setTimeout(()=>arcadeExitSave=false,1500)};
const restore=p=>{Object.assign(MQ.state,p);MQ.state.active=false;MQ.state.timer=null;MQ.state.skills=p.skills||MQ.state.skills;MQ.state.skillStats=p.skillStats||MQ.state.skillStats;MQ.state.account=p.account||MQ.state.account;MQ.state.premium=!!p.premium;MQ.updateGlobal()};
try{const age=Number(localStorage.getItem(AGE_KEY));if(Number.isInteger(age)&&age>=0&&age<MQ.ages.length)MQ.state.age=age;const a=JSON.parse(localStorage.getItem(ACCOUNT_KEY)||'null');if(a)MQ.state.account=a;const st=JSON.parse(localStorage.getItem(SETTINGS_KEY)||'null');if(st)MQ.state.settings=Object.assign(MQ.state.settings||{},st)}catch{}
try{localStorage.setItem(VIEW_KEY,'home')}catch{}
setInterval(save,400);window.addEventListener('beforeunload',save);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')save()});
const homeCard=document.querySelector('#home .card:last-of-type');
if(homeCard){const wrap=document.createElement('div');wrap.id='resume-progress-wrap';wrap.style.cssText='margin-top:14px;display:none;';homeCard.appendChild(wrap);
const render=()=>{const entries=Object.values(saved).filter(p=>p&&p.level>=1&&p.level<=20);if(!entries.length){wrap.style.display='none';return}entries.sort((a,b)=>(b.level-a.level)||(b.xp-a.xp));const p=entries[0];wrap.style.display='block';wrap.innerHTML=`<div class="resume-card"><div><strong>Continue ${gameName(p.game)}</strong><div class="resume-meta">Ages ${MQ.ages[p.age].range} • Level ${p.level}/20 • ${p.xp} XP${p.milestonePending?' • Checkpoint report ready':''}</div></div><button id="resume-last" class="primary-btn" type="button">Resume Game →</button></div>`;document.getElementById('resume-last').onclick=()=>{restore(p);if(p.milestonePending){MQ.showMilestone(p.milestoneLevel||p.level);return}if(p.level>=11&&!MQ.state.account){MQ.showAccountGate();return}const meta={memory:['🧠','Memory Lab','COGNITIVE'],detective:['🔎','Detective','COGNITIVE'],reflex:['⚡','Reflex Arena','PSYCHOMOTOR'],builder:['🧩','Builder','COGNITIVE'],team:['🤝','Team Quest','BEHAVIOURAL'],world:['🌍','World Explorer','COGNITIVE'],money:['💰','Money Mission','COGNITIVE']}[p.game];if(!meta)return;document.getElementById('game-icon').textContent=meta[0];document.getElementById('game-name').textContent=meta[1];document.getElementById('game-skill').textContent=meta[2];document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));document.getElementById('game').classList.add('active');try{localStorage.setItem(VIEW_KEY,'game')}catch{}localStorage.setItem(SESSION,JSON.stringify({age:p.age,game:p.game}));MQ.nextChallenge()};};setTimeout(render,120);setInterval(render,1000)}
document.getElementById('back-home')?.addEventListener('click',()=>saveAndExit(),true);
document.querySelectorAll('.age-btn').forEach((b,i)=>b.addEventListener('click',()=>{try{localStorage.setItem(AGE_KEY,String(i))}catch{}}));
})();
