'use strict';
const fs=require('fs');
const reflex=fs.readFileSync(__dirname+'/../reflex-arena.js','utf8');
const builder=fs.readFileSync(__dirname+'/../builder.js','utf8');
const tests=[];
const check=(name,ok)=>tests.push([name,!!ok]);
check('Reflex precision target accounts for target size',/xMin=.*xMax=.*yMin=.*yMax=/.test(reflex));
check('Reflex precision has bounded board coordinates',/xMin=Math\.max\(10/.test(reflex)&&/yMin=Math\.max\(12/.test(reflex));
check('Builder symmetry has deterministic fallback',/if\(!candidates\.length\)/.test(builder)&&/candidates\.push\(fallback\)/.test(builder));
check('Builder symmetry fallback fills source and mirror',/cells\[fallback\]=true;/.test(builder)&&/cells\[fallbackRow\*n\+\(n-1-fallbackCol\)\]=true;/.test(builder));
check('Builder symmetry always removes the target cell',/cells\[target\]=false;/.test(builder));
check('Tile Match uses a generation token',/S\.builderTileToken=token/.test(builder));
check('Tile Match timer ignores stale generations',/if\(S\.builderTileToken!==token\)return;/.test(builder));
check('Tile Match activates only after memorization',/S\.active=true;/.test(builder)&&/hideAt/.test(builder));
check('Tile Match no longer has an untracked duplicate timeout',!/setTimeout\(\(\)=>\{if\(reveal\)/.test(builder));
for(const [n,ok] of tests)console.log(`${ok?'PASS':'FAIL'} ${n}`);
const failed=tests.filter(([,ok])=>!ok).length;
console.log(`\n${tests.length-failed}/${tests.length} passed`);
process.exitCode=failed?1:0;
