'use strict';
const fs=require('fs');
const reflex=fs.readFileSync(__dirname+'/../reflex-arena.js','utf8');
const tests=[];
const check=(name,ok)=>tests.push([name,!!ok]);
check('Target Rush hides all targets before signal',/b\.disabled=true;b\.textContent=""/.test(reflex));
check('Target Rush randomizes target position each run',/const targetIndex=Math\.floor\(Math\.random\(\)\*count\)/.test(reflex));
check('Target Rush prevents early interaction',/if\(!S\.active\|\|b\.disabled\)return/.test(reflex));
check('Target Rush reveals only the target after the delay',/if\(i===targetIndex\)\{b\.textContent="🎯"/.test(reflex));
check('Target Rush has age-specific wording',/age===0\?\{title:"Catch the Target"/.test(reflex));
check('Target Rush gives preschool players a visual instruction',/Find 🎯 and tap it!/.test(reflex));
check('Target Rush scales target size by age and level',/82-Math\.floor\(S\.level\/4\)\*4-\(age\*3\)/.test(reflex));
check('Target Rush uses an explicit status state',/id="target-status"/.test(reflex)&&/status\.textContent=copy\.go/.test(reflex));
check('Target Rush clears its countdown timer when signal fires',/clearInterval\(countdownTimer\)/.test(reflex));
check('Target Rush keeps reaction timing age-scaled',/responseWindow\(\.9\)/.test(reflex));
for(const [n,ok] of tests)console.log(`${ok?'PASS':'FAIL'} ${n}`);
const failed=tests.filter(([,ok])=>!ok).length;
console.log(`\n${tests.length-failed}/${tests.length} passed`);
process.exitCode=failed?1:0;
