const fs=require('fs'),path=require('path');
const ROOT=path.resolve(__dirname,'..');
const read=f=>fs.readFileSync(path.join(ROOT,f),'utf8');
let pass=0,fail=0;const ok=(n,c,d='')=>{c?pass++:fail++;console.log(`${c?'PASS':'FAIL'} ${n}${d?` [${d}]`:''}`)};
const team=read('team-quest.js'),world=read('world-explorer.js'),money=read('money-mission.js'),detective=read('detective.js'),reflex=read('reflex-arena.js'),builder=read('builder.js');
const types=(team.match(/const TYPES=\[([\s\S]*?)\];/)||[])[1]||'';
const expected=['choice','order','match','plan','empathy','responsibility','communication','negotiation','conflict','leadership','actionSequence','tradeoff','activeListening','perspective'];
for(const t of expected)ok(`Team Quest mechanic: ${t}`,types.includes(`'${t}'`)||types.includes(`"${t}"`));
ok('Team Quest has a real action-sequence activity',/type==='actionSequence'/.test(team)&&/order\(type,ORDERS/.test(team));
ok('Team Quest includes plausible communication scenarios',/COMMUNICATION=/.test(team)&&/Could you explain/.test(team));
ok('World Explorer uses globally distributed direction examples',/Berlin is east of Paris/.test(world)&&/Toronto is west of New York City/.test(world));
ok('World Explorer uses distinct distance distractors',/vals=\[base,base\+5\+\(activity\(\)\*2\),base\+13\]/.test(world));
ok('Money Mission guarantees four savings options',/\[correct,wk\(weeks\+1\),wk\(weeks\+2\),weeks>1\?wk\(weeks-1\):wk\(weeks\+3\)\]/.test(money));
ok('Money Mission exact change supports undo and clear',/change-undo/.test(money)&&/change-clear/.test(money));
ok('Detective probability includes fraction reasoning',/probability of red\?','3\/5/.test(detective)&&/2\/5/.test(detective));
ok('Reflex advanced mechanics are reachable',/\"mirror\".*\"chase\"/.test(reflex)&&/type===\"chase\"/.test(reflex));
ok('Builder balance has a single defensible answer',/const left=4\+tier\(\)\+\(S\.level%5\),right=2\+/.test(builder)&&/data-v=\"\$\{v\}\"/.test(builder));

ok('Reflex rhythm uses two response controls',/rhythm-controls/.test(reflex)&&/data-v=\"●\"/.test(reflex)&&/data-v=\"○\"/.test(reflex));
ok('Reflex double target prevents identical positions',/second=\(first\+2\+activity\(\)\)%count===first/.test(reflex));
ok('Builder rotation displays first three and expects fourth',/v\.slice\(0,3\)/.test(builder)&&/correct=v\[3\]/.test(builder));
ok('Builder tile match always has at least one target cell',/if\(!target\.size\)target\.add/.test(builder));
console.log(`\n${pass} passed, ${fail} failed`);process.exit(fail?1:0);
